/*
 * This source file was generated by the Gradle 'init' task
 */
package ticket.booking;

import java.util.Arrays;
import java.util.List;

import java.util.function.Predicate;
import java.util.stream.Collectors;

public class App {

    public static void main(String[] args) {
        System.out.println();
//        List<Integer> l = Arrays.asList(1,2,3,4,5,6);
////        List<Integer> l1 = l.stream().filter(i-> i%2==0).collect(Collectors.toList());
//
//        // Way 2
//        List<Integer> l1 = l.stream().filter(isEven()).collect(Collectors.toList());
//
//        // Map
//        l.stream().map(e->e*2).collect(Collectors.toList());
//        // This takes e as input and returns e*2


    }
    // as filter internally requires predicate method, we have written that.
//        public static Predicate<Integer> isEven(){
//        return i -> i%2==0;
//        }

}
